spring:
  datasource:
    #    url: jdbc:h2:file:./springboot-spring-data-jpa-persisting-entities/db/trainers-db
    #    url: jdbc:postgresql://localhost:5432/planets_db?currentSchema=planets_user
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: trainer_user
    password: trainer_user
  #    driver-class-name: org.postgresql.Driver
  application:
    name: springboot-spring-data-jpa-persisting-entities
  jpa:
    #    database-platform: org.hibernate.dialect.Oracle
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 10


server:
  port: 8082

