scrape_configs:
  - job_name: 'springboot-jpa-stream'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Spring JPA Stream'