create table GEMS
(
    id      bigint generated by default as identity,
    rrn      RAW(16)     default  SYS_GUID(),
    clarity varchar(255) NOT NULL,
    color varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    cut varchar(255) NOT NULL,
    primary key (id)
)