create table gems
(
    id           bigint generated by default as identity,
    clarity      varchar(255),
    color        varchar(255),
    created_date timestamp(6) with time zone,
    cut          varchar(255),
    name         varchar(255),
    prices       JSON,
    rrn          uuid,
    status       varchar(255) check (status in ('ACTIVE', 'INACTIVE')),
    primary key (id)
);
create table histories
(
    id               uuid not null,
    owner            varchar(255),
    transferred_date timestamp(6) with time zone,
    gem_id           bigint,
    primary key (id)
);
alter table if exists histories
    add constraint FKjtq10s2x4fs9dxl29wdnyox9 foreign key (gem_id) references gems;


insert into gems (id, clarity, color, cut, name, rrn, status)
values (1, 'MEDIUM', 'RED', 'round', 'Emerald', 'aa9f9d5a-38ab-4d22-9055-c0db621fc879', 'INACTIVE');