spring:
  application:
    name: springboot-jpa-stream
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 100000

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
