spring:
  application:
    name: springboot-jpa-structural-concurrency
  threads:
    virtual:
      enabled: true
  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 100_000