server:
  port: 8081

app:
  datasource:
    secondary:
      url: jdbc:h2:file:./springboot-multiple-datasources/db/db-2
      jdbcUrl: jdbc:h2:file:./springboot-multiple-datasources/db/db-2
      driverClassName: org.h2.Driver
      configuration:
        maximum-pool-size: 30

spring:
  datasource:
    url: jdbc:h2:file:./springboot-multiple-datasources/db/db-1
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 30
  jpa:

    properties:
      #      hibernate-ddl-auto: create-drop
      hibernate.hbm2ddl.auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

