logging:
  level:
    com.fabiankevin: DEBUG

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        order_updates: true
        generate_statistics: true
        jdbc:
          batch_size: 5000